### ISSUE TITLE
Error on startup (1.13.2)

### ISSUE THREAD

**Issue by KamosRZ** [EvModder/DropHeads#1]
Hello,

When the server starts the plugin fails to load because it is looking for a plugin that I don't have - RPGInventories.

[10:06:51] [Server thread/ERROR]: Error occurred while enabling DropHeads v3.2.6 (Is it up to date?)
java.lang.NoClassDefFoundError: Lru/endlesscode/rpginventory/RPGInventory;
.
.
Caused by: java.lang.ClassNotFoundException: ru.endlesscode.rpginventory.RPGInventory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-624]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-624]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 18 more

**Comment by KamosRZ** [comment]
I managed to "fix" it by creating a folder called EvFolder in my ./plugins folder.

**Comment by EvModder** [comment]
Oof yeah that looks gross.
I actually have no idea what RPGInventory is, but I think I may have fixed some lingering issues with EvLib/EvFolder in the stable release for 1.14 (finally public today)

**Comment by EvModder** [comment]
After thorough testing I think it is safe to say error was fixed in the EvLib update in May
