### ISSUE TITLE
Could not pass event PlayerDeathEvent to DropHeads

### ISSUE THREAD

**Issue by tomkimberlin** [EvModder/DropHeads#102]
Getting the following error on 1.20.2

```
[23:12:48 ERROR]: Could not pass event PlayerDeathEvent to DropHeads v3.8.1
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
        at net.evmodder.DropHeads.JunkUtils.getGameProfile(JunkUtils.java:340) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:689) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:746) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:666) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:689) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:196) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:289) ~[DropHeads.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-233]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-233]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-233]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:958) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:963) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1551) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:973) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1132) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1326) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2175) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2777) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2701) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-233]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-233]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by EvModder** [comment]
Alright so I think I have a working fix, but I won't be able to test it personally until I can get my test server working (I'll bother with that sometime tomorrow or this weekend perhaps)

I went ahead and updated the [dev build jar](https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.8.2.jar) though, so if you want you can give it a try and LMK if it works :)

**Comment by tomkimberlin** [comment]
> Alright so I think I have a working fix, but I won't be able to test it personally until I can get my test server working (I'll bother with that sometime tomorrow or this weekend perhaps)
> 
> I went ahead and updated the [dev build jar](https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.8.2.jar) though, so if you want you can give it a try and LMK if it works :)

Dev build works great. Thanks!
