### ISSUE TITLE
There is problem with Unable to find skin for player

### ISSUE THREAD

**Issue by smscentras** [EvModder/DropHeads#103]
[14:03:38 WARN]: [DropHeads] Unable to find skin for player: GGxxHHacker
[14:03:38 WARN]: [DropHeads] num textures: 0
[14:03:38 ERROR]: Could not pass event PlayerDeathEvent to DropHeads v3.8.1
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:366) ~[DropHeads.jar:?]
        at net.evmodder.EvLib.extras.NBTTagUtils.getTag(NBTTagUtils.java:215) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.JunkUtils.setLore(JunkUtils.java:90) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:716) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:746) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:666) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:689) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:196) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:289) ~[DropHeads.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:925) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:917) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:124) ~[paper-1.19.4.jar:git-Paper-550]
        at me.realized.duels.duel.DuelManager$DuelListener.on(DuelManager.java:631) ~[Duels-3.5.3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:592) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2121) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:533) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:474) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:612) ~[paper-1.19.4.jar:git-Paper-550]
        at com.Zrips.CMI.commands.list.kick.perform(kick.java:115) ~[CMI-9.6.6.0.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[CMI-9.6.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1168) ~[CMI-9.6.6.0.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1057) ~[CMI-9.6.6.0.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404) ~[CMI-9.6.6.0.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:308) ~[CMI-9.6.6.0.jar:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:252) ~[CMI-9.6.6.0.jar:?]
        at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:255) ~[CMI-9.6.6.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1002) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at me.frep.vulcan.spigot.Vulcan_Bm.Vulcan_j(Vulcan_Bm.java:108) ~[Vulcan-2.7.7.jar:?]
        at me.frep.vulcan.spigot.Vulcan_t2.lambda$run$0(Vulcan_t2.java:235) ~[Vulcan-2.7.7.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.frep.vulcan.spigot.Vulcan_t2.run(Vulcan_t2.java:207) ~[Vulcan-2.7.7.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:364) ~[DropHeads.jar:?]
        ... 52 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:473) ~[?:?]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:721) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:709) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:28) ~[paper-1.19.4.jar:git-Paper-550]
        at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:364) ~[DropHeads.jar:?]
        ... 52 more

**Comment by EvModder** [comment]
Hmm, is this on an offline mode server?
Also, there's a v3.8.2 jar (available on the GitHub right now, should be out on Bukkit as well in a day or two) where I fixed a very similar issue, so if you can give that version a try and let me know if the problem still happens that would be appreciated.

If the issue still happens then maybe Mojang has changed something about their skin server API again... which I hope isn't the case because that's always a pain but I can figure it out

**Comment by smscentras** [comment]
This problem not allways, don't know when and why.
Yes, server is offline mode server. Downloaded your v.3.8.2, we will see later.

**Comment by EvModder** [comment]
I'm going to mark this issue as closed for now since I think 3.8.2 should have fixed it and haven't heard any other reports, but if it keeps happening, LMK by replying (it will reopen the bug).
