### ISSUE TITLE
ERROR: Could not pass event ItemSpawnEvent to DropHeads v3.8.2

### ISSUE THREAD

**Issue by smscentras** [EvModder/DropHeads#104]
[13:30:12 ERROR]: Could not pass event ItemSpawnEvent to DropHeads v3.8.2
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:366) ~[DropHeads_v3.8.2.jar:?]
        at net.evmodder.EvLib.extras.NBTTagUtils.getTag(NBTTagUtils.java:215) ~[DropHeads_v3.8.2.jar:?]
        at net.evmodder.DropHeads.JunkUtils.setLore(JunkUtils.java:90) ~[DropHeads_v3.8.2.jar:?]
        at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:720) ~[DropHeads_v3.8.2.jar:?]
        at net.evmodder.DropHeads.listeners.ItemDropListener.onBarf(ItemDropListener.java:62) ~[DropHeads_v3.8.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1213.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-246]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-246]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-246]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:817) ~[paper-1.20.2.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:695) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1690) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1598) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1593) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2346) ~[?:?]
        at net.minecraft.world.entity.player.Player.drop(Player.java:719) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:523) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3109) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-246]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor36.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:364) ~[DropHeads_v3.8.2.jar:?]
        ... 37 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:510) ~[?:?]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:744) ~[paper-1.20.2.jar:git-Paper-246]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:732) ~[paper-1.20.2.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:46) ~[paper-1.20.2.jar:git-Paper-246]
        at jdk.internal.reflect.GeneratedMethodAccessor36.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:364) ~[DropHeads_v3.8.2.jar:?]
        ... 37 more

**Comment by EvModder** [comment]
Hmm, it doesn't happen for me, so I'll need a few more details to figure it out.
Does it only happen for player behead, mob behead, or both?
Does it only happen in combination with another plugin that edits mob drops / item spawns (compatibility issue)?
any steps to recreate would be helpful, also whether this happens with default config or only with specific settings enabled (in which case LMK)

**Comment by smscentras** [comment]
[20:09:37 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
[20:09:37 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

I don't know where from that :(

**Comment by satadrive420** [comment]
I am getting a similar error when bedrock players connected through Geyser/Floodgate are killed. 

08.11 01:33:37 [Server] ERROR Could not pass event PlayerDeathEvent to DropHeads v3.8.2
08.11 01:33:37 [Server] INFO java.lang.StringIndexOutOfBoundsException: begin 44, end -1, length 0
08.11 01:33:37 [Server] INFO at java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[?:?]
08.11 01:33:37 [Server] INFO at java.lang.String.substring(String.java:2709) ~[?:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.HeadAPI.minimizeTextureCode(HeadAPI.java:586) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:705) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:750) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:666) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:689) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:196) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:289) ~[DropHeads (1).jar:?]
08.11 01:33:37 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1996]
08.11 01:33:37 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
08.11 01:33:37 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1996]
08.11 01:33:37 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1996]
08.11 01:33:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
08.11 01:33:37 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:934) ~[purpur-1.20.1.jar:git-Purpur-1996]
08.11 01:33:37 [Server] INFO at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:979) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1573) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.world.entity.player.Player.hurt(Player.java:1006) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1165) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.world.entity.player.Player.attack(Player.java:1359) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2284) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2971) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2893) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
08.11 01:33:37 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]

**Comment by satadrive420** [comment]
To add to this, for my issue it looks like the plugin errors out when attempting to pull a head texture for a Floodgate UUID (since they're not associated with a valid player).

**Comment by EvModder** [comment]
Thanks for the details, the Geyser/Floodgate errors are especially helpful since it pinpoints the source of the error.

> [20:09:37 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

This error message is strange to me, since DropHeads uses the API for textures (and does it the same way as basically all other head plugins), so I'll have to look into it once i set up a Geyser test server tonight/tomorrow

**Comment by EvModder** [comment]
I've had a bit of trouble getting Geyser working on my PC, partly because I need to update my Minecraft version & fabric mods, so I'll look at it more tomorrow or Thursday when I get some time, but I added some detailed error messages + an attempt to fix the issue when the UUID is unknown, so if you'd like to try out the dev jar and see if it works feel free, I'll link it here:
https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.8.3.jar

**Comment by EvModder** [comment]
The updated version is also available on Bukkit now if you want to give it a try, and LMK if it fixed the issue :)

**Comment by EvModder** [comment]
Closing this now since it's been ~4 months, and so far I haven't seen this issue crop up again, but please reopen if you notice it again or find any other way to trigger it
