### ISSUE TITLE
Could not pass event EntityTargetLivingEntityEvent to DropHeads v3.9.0

### ISSUE THREAD

**Issue by tbm00** [EvModder/DropHeads#108]
This is spamming the console. Using 1.20.4 purpur.

Could not pass event EntityTargetLivingEntityEvent to DropHeads v3.9.0
java.lang.ClassCastException: class org.bukkit.event.entity.EntityDamageEvent cannot be cast to class org.bukkit.event.entity.EntityDamageByEntityEvent (org.bukkit.event.entity.EntityDamageEvent and org.bukkit.event.entity.EntityDamageByEntityEvent are in unnamed module of loader java.net.URLClassLoader @525f1e4e)
        at net.evmodder.DropHeads.listeners.EndermanProvokeListener.entityTargetEntityEvent(EndermanProvokeListener.java:55) ~[DropHeads.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor651.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2149]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.Mob.setTarget(Mob.java:318) ~[?:?]
        at net.minecraft.world.entity.monster.EnderMan.setTarget(EnderMan.java:164) ~[?:?]
        at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.start(NearestAttackableTargetGoal.java:71) ~[?:?]
        at net.minecraft.world.entity.monster.EnderMan$EndermanLookForPlayerGoal.tick(EnderMan.java:722) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:157) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:148) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:956) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3500) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:706) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.EnderMan.aiStep(EnderMan.java:316) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3149) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:462) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:940) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:917) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1749) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by EvModder** [comment]
I think I've found and fixed the problem, if you want to give the [dev build](https://github.com/EvModder/DropHeads/raw/master/DropHeads_v3.9.1.jar) a try and let me know.
I'll also be update it for the main release jar on Bukkit.com later this week (once I finish redoing some textures for the snapshots and testing some new features).

**Comment by EvModder** [comment]
Let me know if this issue still occurs or shows up again - closing this bug for now
