### ISSUE TITLE
Drop Heads "Could not pass event EntityDeathEvent to dropheads v3.9.4" - 1.20.6 Paper

### ISSUE THREAD

**Issue by Midnighttigger** [EvModder/DropHeads#110]
heres the log: (was run on aternos)
<html><body>

  | [13:05:41] [Server thread/ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.9.4
-- | --
 

<span class="level level-error multiline">	... 38 more</span>
</body>
</html>

**Comment by Midnighttigger** [comment]
[loga.txt](https://github.com/EvModder/DropHeads/files/15434020/loga.txt) the part of the log didnt upload correctly so here it is

**Comment by EvModder** [comment]
Sorry for the late reply! - Apparently GitHub doesn't send me push notifications anymore... thanks Microsoft.

Anyways, it looks like the error is from the plugin trying to fetch item custom names (for behead messages) from the new 1.20.6+ components field, and when the item doesn't have a name the internal Mojang library for processing text panics due to null value.

Idk if that makes any sense, but tl;dr it should be a pretty quick fix, I can go ahead and edit + publish it right now

**Comment by FastJoe0** [comment]
still not working:

```
[18:50:59 INFO]: [DropHeads] Enabling DropHeads v3.9.4
[18:50:59 ERROR]: Error occurred while enabling DropHeads v3.9.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at DropHeads-3.9.4.1.jar/net.evmodder.DropHeads.DropHeads.onEvEnable(DropHeads.java:84) ~[DropHeads-3.9.4.1.jar:?]
        at DropHeads-3.9.4.1.jar/net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:43) ~[DropHeads-3.9.4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-95-5e7b65a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: no such method
        at DropHeads-3.9.4.1.jar/net.evmodder.EvLib.extras.ReflectionUtils$RefClass.findMethod(ReflectionUtils.java:194) ~[DropHeads-3.9.4.1.jar:?]
        at DropHeads-3.9.4.1.jar/net.evmodder.DropHeads.JunkUtils.<clinit>(JunkUtils.java:226) ~[DropHeads-3.9.4.1.jar:?]
        ... 14 more
[18:50:59 INFO]: [DropHeads] Disabling DropHeads v3.9.4
```

**Comment by Midnighttigger** [comment]
Sorry for the late reply, I reported it because we were going to use 1.20.6 with mob heads but then we decided to stick with 1.20.4 for now so I do not use this plugin anymore however this issue can still be used to improve the plugin if you want.

**Comment by EvModder** [comment]
Thanks and no worries, it's always good to keep stuff tracked. I was able to fix the bug the same day as my last comment and haven't had any further reports of issues from anyone else so I think it's safe to mark resolved.
