### ISSUE TITLE
DropHeads v3.9.4.1 startup problem

### ISSUE THREAD

**Issue by FastJoe0** [EvModder/DropHeads#111]
default settings:

```
[18:50:59 INFO]: [DropHeads] Enabling DropHeads v3.9.4
[18:50:59 ERROR]: Error occurred while enabling DropHeads v3.9.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at DropHeads-3.9.4.1.jar/net.evmodder.DropHeads.DropHeads.onEvEnable(DropHeads.java:84) ~[DropHeads-3.9.4.1.jar:?]
        at DropHeads-3.9.4.1.jar/net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:43) ~[DropHeads-3.9.4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-129-0513374]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: no such method
        at DropHeads-3.9.4.1.jar/net.evmodder.EvLib.extras.ReflectionUtils$RefClass.findMethod(ReflectionUtils.java:194) ~[DropHeads-3.9.4.1.jar:?]
        at DropHeads-3.9.4.1.jar/net.evmodder.DropHeads.JunkUtils.<clinit>(JunkUtils.java:226) ~[DropHeads-3.9.4.1.jar:?]
        ... 14 more
[18:50:59 INFO]: [DropHeads] Disabling DropHeads v3.9.4
```

**Comment by EvModder** [comment]
Oh dear... looks like I uploaded the wrong jar to Bukkit, so everyone is probably getting this crash. Thanks for letting me know, fixing it right now
