### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Teddy293** [EvModder/DropHeads#117]
My console gets spammed with this error I'm not sure how to fix it

[13:11:32 ERROR]: Could not pass event ItemSpawnEvent to DropHeads v3.9.8
java.lang.IllegalArgumentException: Can not set com.mojang.authlib.GameProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to net.minecraft.world.item.component.ResolvableProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at DropHeads.jar/net.evmodder.EvLib.extras.HeadUtils.setGameProfile(HeadUtils.java:155) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.EvLib.extras.HeadUtils.makeCustomHead(HeadUtils.java:192) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:761) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.DropHeads.listeners.ItemDropListener.onBarf(ItemDropListener.java:62) ~[DropHeads.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1735.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:1.21-7-469e5c1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:820) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at org.bukkit.craftbukkit.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:700) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1555) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1480) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1475) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2848) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2834) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2793) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Entity.spawnAtLocation(Entity.java:2787) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Mob.equipItemIfPossible(Mob.java:751) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Mob.pickUpItem(Mob.java:710) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:696) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:273) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3199) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.Mob.tick(Mob.java:447) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:241) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1262) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:740) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1813) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1605) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1305) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[pufferfish-1.21.jar:1.21-7-469e5c1]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by EvModder** [comment]
I've published a new jar, v3.9.8.1, which should fix this bug (99% certain, although I haven't tested it for all server types).

It will be available on Bukkit within a couple hours/days, or here on the GitHub rn.
