### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Teddy293** [EvModder/DropHeads#119]
[23:07:52 ERROR]: Could not pass event ItemSpawnEvent to DropHeads v3.9.8.1
java.lang.NullPointerException: Profile name must not be null
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-6.0.54.jar:?]
        at DropHeads.jar/net.evmodder.EvLib.extras.HeadUtils.convertFromResolveProfileIfNeeded(HeadUtils.java:143) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.EvLib.extras.HeadUtils.getGameProfile(HeadUtils.java:174) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.DropHeads.listeners.ItemDropListener.onBarf(ItemDropListener.java:60) ~[DropHeads.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1775.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:826) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at org.bukkit.craftbukkit.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:706) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1555) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1480) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1475) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.spawnItem(DefaultDispenseItemBehavior.java:113) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.execute(DefaultDispenseItemBehavior.java:47) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.dispense(DefaultDispenseItemBehavior.java:34) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.world.level.block.DropperBlock.dispenseFrom(DropperBlock.java:75) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.world.level.block.DispenserBlock.tick(DispenserBlock.java:141) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1222) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1206) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:673) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1811) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:476) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[pufferfish-1.21.1.jar:1.21.1-21-cfa3c61]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        
        
        Anyway to fix this or is it a known issue getting fixed or maybe something in my config is messed up possibly?

**Comment by EvModder** [comment]
Ah yeah, it's a known issue, it's fixed in v3.9.9 which is available [here](https://github.com/EvModder/DropHeads/blob/master/DropHeads_v3.9.9.jar) but I haven't published it to Bukkit yet (because there's another issue for people migrating from old versions of DropHeads, v3.8.2 or earlier, but in your case that doesn't matter)

**Comment by EvModder** [comment]
Marking this bug as closed now that v3.9.9 is publicly released on Bukkit
