### ISSUE TITLE
Incompatibility with HeadDatabase (?)

### ISSUE THREAD

**Issue by MaksyKun** [EvModder/DropHeads#120]
Greetings,
when people drop their heads from HeadDatabase which are modified with name/lore/etc., DropHeads throws an expection:

```
[12:10:13 ERROR]: Could not pass event ItemSpawnEvent to DropHeads v3.9.9
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143) ~[?:?]
        at DropHeads.jar/net.evmodder.EvLib.extras.HeadUtils.convertFromResolvedProfile(HeadUtils.java:125) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.EvLib.extras.HeadUtils.getGameProfile(HeadUtils.java:154) ~[DropHeads.jar:?]
        at DropHeads.jar/net.evmodder.DropHeads.listeners.ItemDropListener.onBarf(ItemDropListener.java:60) ~[DropHeads.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor837.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:835) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:715) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1623) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1548) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1543) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleBlockDropItemEvent(CraftEventFactory.java:479) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:459) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1934) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

This leads to the problem, that heads from HDB become steve/alex textures which breaks those heads. However, some people can still see the original texture which is not explainable atm. It could also be something else regarding to HDB itself but I'd like to debug from small to big reasons.

Best Regards,
~Maksy

**Comment by EvModder** [comment]
Oh that's very strange - based on the error, apparently there are heads without any UUID attached, which I thought was impossible. I'll take a deeper look when I get home (running it with HDB on my test server).

I definitely want to fix compatibility since HDB and DH used to work fine together and I don't want any regressions.

**Comment by EvModder** [comment]
It is a bit difficult for me to be 100% certain I've fixed it since I don't own HeadDatabase myself, but I think I've resolved the most likely issue, which is that DropHeads was using HDB API 1.3.2 not 1.3.3

If you're able to give it a try and let me know if it's fixed, that'd be great. Jar is named DropHeads_v3.9.10 and it's on the main folder of this repo (or you can grab it [here](https://github.com/EvModder/DropHeads/blob/master/DropHeads_v3.9.10.jar))

**Comment by MaksyKun** [comment]
I have updated DropHeads now and gonna track it down after our next global restart. Gonna let you know once I figure something out. Thanks for the efforts 👍

**Comment by MaksyKun** [comment]
The error is not happening anymore. Instead, I found out that some heads which are a bit older than the newest HDB versions leads to texture loss when the head is dropped or broken as block (except of players heads).

Newer heads are working as expected, but this is definetly a HDB problem. Thank for fixing the other error!

**Comment by EvModder** [comment]
Ah ok, glad to hear it out of my bucket 😅 and hopefully the HDB author is able to retroactively resolve those issues as well, fingers crossed for you.

Mojang semi-recently reworked a lot of the backend components and validation for custom heads, so everyone's been catching up with the changes
