### ISSUE TITLE
Could not pass event BlockBreakEvent to DropHeads v3.2.10

### ISSUE THREAD

**Issue by aSlug** [EvModder/DropHeads#2]
The following error appeared in the server logs when a player broke a head block generated via command `/gethead`

```
[13:17:30] [Server thread/ERROR]: Could not pass event BlockBreakEvent to DropHeads v3.2.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:230) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.IllegalArgumentException: UUID cannot be null
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getOfflinePlayer(CraftServer.java:1344) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:137) ~[?:?]
at net.evmodder.DropHeads.listeners.BlockBreakListener.onBlockBreakEvent(BlockBreakListener.java:27) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-94af569-a3fdef8]
... 20 more
```

**Comment by EvModder** [comment]
Hmm what type of head was it?
I'm about to release a new version (with textures for the 1.15 heads) but if this bug is still in there it would be good to fix it first :)

also, sorry for taking so long to reply.

**Comment by EvModder** [comment]
I haven't been able to reproduce, but I've tweaked the HeadAPI to check for null so that this error won't appear in the console.  It's a harmless error from what I can tell anyways, and shouldn't affect the head.

**Comment by aSlug** [comment]
It was a Steve head and if i remember correctly it was generated by the player using only the command `/gethead` with no argument. The error was triggered when the player placed the head and then mined it.

The error was indeed harmless, I verified that all heads dropped by mobs and players are working perfectly.

**Comment by EvModder** [comment]
Ok, thanks for letting me know!
``/gethead`` with no argument gives the head of the sender, but if they didn't have a custom skin then this could happen.. fixed now.
