### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by d3kv** [EvModder/DropHeads#25]
I keep getting this on my console from time to time and it annoys me, is there any issue with my cfg?
Could not pass event PlayerInteractEvent to DropHeads v3.5.2
java.lang.NullPointerException: null
	at java.util.TreeMap.getEntry(TreeMap.java:345) ~[?:?]
	at java.util.TreeMap.containsKey(TreeMap.java:231) ~[?:?]
	at net.evmodder.DropHeads.HeadAPI.getHeadNameData(HeadAPI.java:202) ~[?:?]
	at net.evmodder.DropHeads.listeners.BlockClickListener.onBlockClickEvent(BlockClickListener.java:54) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-366]
	at org.bukkit.plugin.EventExecutor$$Lambda$4643.000000008D38B4B0.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-366]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-366]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-366]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5894.0000000044064060.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-366]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3144.000000009D757E20.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]

**Comment by MageAtoru** [comment]
> I keep getting this on my console from time to time and it annoys me, is there any issue with my cfg?
> Could not pass event PlayerInteractEvent to DropHeads v3.5.2
> java.lang.NullPointerException: null
> at java.util.TreeMap.getEntry(TreeMap.java:345) ~[?:?]
> at java.util.TreeMap.containsKey(TreeMap.java:231) ~[?:?]
> at net.evmodder.DropHeads.HeadAPI.getHeadNameData(HeadAPI.java:202) ~[?:?]
> at net.evmodder.DropHeads.listeners.BlockClickListener.onBlockClickEvent(BlockClickListener.java:54) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-366]
> at org.bukkit.plugin.EventExecutor$$Lambda$4643.000000008D38B4B0.execute(Unknown Source) ~[?:?]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-366]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-366]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-366]
> at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5894.0000000044064060.run(Unknown Source) ~[?:?]
> at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-366]
> at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3144.000000009D757E20.run(Unknown Source) ~[?:?]
> at java.lang.Thread.run(Thread.java:835) [?:?]

getting the exact same error...
everything works, players are getting mob heads but from time to time I get the exact error message

**Comment by Uranusak** [comment]
[15:44:23 ERROR]: Could not pass event PlayerDeathEvent to DropHeads v3.5.2
java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Matcher.java:857) ~[?:1.8.0_262]
        at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_262]
        at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_262]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.getItemDisplay(EntityDeathListener.java:325) ~[?:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.dropHead(EntityDeathListener.java:394) ~[?:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:536) ~[?:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:576) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-406]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:834) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:675) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1267) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EnchantmentThorns.b(SourceFile:50) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EnchantmentManager.lambda$a$4(EnchantmentManager.java:140) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EnchantmentManager.lambda$a$1(EnchantmentManager.java:96) ~[patched_1.16.4.jar:git-Paper-406]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_262]
        at net.minecraft.server.v1_16_R3.EnchantmentManager.a(EnchantmentManager.java:95) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EnchantmentManager.a(EnchantmentManager.java:109) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EnchantmentManager.a(EnchantmentManager.java:144) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1168) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1834) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2249) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1257) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-406]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-406]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by EvModder** [comment]
That looks like an different error from the original, what sort of mobs does it happen for?
(sorry for the slow response)

**Comment by MageAtoru** [comment]
I have to say that I did not get any of this errors in last week or so - no clue why as to nothing changed on our server...

**Comment by EvModder** [comment]
Oh, perhaps this was fixed in the last update, with auto-update turned on perhaps it silently fixed itself...
We'll wait a while and see though
