### ISSUE TITLE
Update to 1.16.5 needed

### ISSUE THREAD

**Issue by Jacold** [EvModder/DropHeads#26]
Hello. DH won't start on 1.16.5 server. Here's log:
`[01:24:07 ERROR]: Error occurred while enabling DropHeads v3.5.2 (Is it up to date?)
java.lang.NullPointerException: null
        at net.evmodder.DropHeads.commands.CommandDropRate.<init>(CommandDropRate.java:35) ~[?:?]
        at net.evmodder.DropHeads.DropHeads.onEvEnable(DropHeads.java:100) ~[?:?]
        at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:30) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-434]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-434]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-434]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-434]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-434]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-434]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by EvModder** [comment]
Oh, that's an issue unrelated to 1.16.5, it's a bug for invalid configs that got fixed recently.
It's already updated on `[Bukkit.org](https://dev.bukkit.org/projects/dropheads/files)`, it looks like you have automatic updates turned off but you can go to that link and download the latest version
