### ISSUE TITLE
Not running right in java 15 on paper spigot

### ISSUE THREAD

**Issue by AustinGarrettR** [EvModder/DropHeads#34]
Format error occurs when typing the command /droprate [entity]

`
org.bukkit.command.CommandException: Unhandled exception executing command 'droprate' in plugin DropHeads v3.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-638]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2171) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1986) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1939) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-638]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-638]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.UnknownFormatConversionException: Conversion = '%'
        at java.util.Formatter.checkText(Formatter.java:2732) ~[?:?]
        at java.util.Formatter.parse(Formatter.java:2718) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2655) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2609) ~[?:?]
        at java.lang.String.format(String.java:2897) ~[?:?]
        at net.evmodder.DropHeads.commands.CommandDropRate.onCommand(CommandDropRate.java:132) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-638]
        ... 19 more
`

My assumption is that it's due to the trailing % symbol at the end of this line on line 32 in the same file:
`	final String DROP_CHANCE_FOR = "Â§6Drop chance for Â§e%sÂ§6: Â§b%s%";`

**Comment by AustinGarrettR** [comment]
Note: I did attempt to compile the fix myself, but it appears there is a reference to a user-made library that is supplied with an out of date version. 
![image](https://user-images.githubusercontent.com/42952632/116775122-64b11600-aa1e-11eb-8dda-f20c189f9577.png)

**Comment by EvModder** [comment]
Ahh yeah I see, I'll go ahead and fix that.  Sorry for the slow response.  I'll correct the library version as well

**Comment by EvModder** [comment]
Turns out this affects all other java versions as well, not sure how I missed it 😅
Oh well, I was able to fix it.
It might take a while for the new .jar to upload to curseforge/Bukkit

**Comment by AustinGarrettR** [comment]
> Turns out this affects all other java versions as well, not sure how I missed it 😅
> Oh well, I was able to fix it.
> It might take a while for the new .jar to upload to curseforge/Bukkit

Thank you!
