### ISSUE TITLE
Error while attempting to load on 1.17

### ISSUE THREAD

**Issue by Carbuino** [EvModder/DropHeads#42]
I get this error when attempting to load on 1.17
I'm running Spigot 1.17 on Java 16
```
[17:10:44] [Server thread/INFO]: [DropHeads] Enabling DropHeads v3.6.6
[17:10:44] [Server thread/ERROR]: Error occurred while enabling DropHeads v3.6.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.evmodder.DropHeads.listeners.EntityDeathListener.<init>(EntityDeathListener.java:121) ~[?:?]
        at net.evmodder.DropHeads.DropHeads.onEvEnable(DropHeads.java:60) ~[?:?]
        at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:29) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[Spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: no class found: net.minecraft.server.dedicated.ItemStack
        at net.evmodder.EvLib.extras.ReflectionUtils.getRefClass(ReflectionUtils.java:81) ~[?:?]
        at net.evmodder.DropHeads.JunkUtils.<clinit>(JunkUtils.java:96) ~[?:?]
        ... 13 more
```

**Comment by mentaldaveuk** [comment]
Same for me too :(

**Comment by CowtealM** [comment]
Same as well

**Comment by Tuurkevg** [comment]
Same as well!

**Comment by EvModder** [comment]
Sorry everyone!  I didn't realize it broke in 1.17 and I've been distracted the last week, but I fixed it and a new version has been uploaded (v3.6.7) which will be compatible with 1.13 - 1.17 :)

**Comment by mentaldaveuk** [comment]
Awesome thanks :D
