### ISSUE TITLE
1.17 error:

### ISSUE THREAD

**Issue by thiagogebrim13** [EvModder/DropHeads#43]
```
[21:48:08 ERROR]: Error occurred while enabling DropHeads v3.6.7 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.permissions.Permission.getName()" because "alwaysBeheadPerm" is null
        at net.evmodder.DropHeads.listeners.EntityDeathListener.<init>(EntityDeathListener.java:298) ~[?:?]
        at net.evmodder.DropHeads.DropHeads.onEvEnable(DropHeads.java:60) ~[?:?]
        at net.evmodder.EvLib.EvPlugin.onEnable(EvPlugin.java:29) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Purpur-1218]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Purpur-1218]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Purpur-1218]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Purpur-1218]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.jar:git-Purpur-1218]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2315) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2126) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2107) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1360) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[patched_1.17.jar:git-Purpur-1218]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1218]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[21:48:08 INFO]: [DropHeads] Disabling DropHeads v3.6.7
```

**Comment by EvModder** [comment]
Hmm, this looks like an error with files inside the DropHeads.jar, perhaps the `plugin.yml` file got corrupted somehow. I've added a check for this when the plugin loads so it won't fail in this particular case, and I've also uploaded a `v3.6.8` jar update in case the one currently on the website is corrupted in some way.
