### ISSUE TITLE
Server completely crashes when "killing" an armor stand with the permission "dropheads.alwaysbehead"

### ISSUE THREAD

**Issue by Eloujah** [EvModder/DropHeads#45]
`[23:28:06] [Server thread/ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@14e801ea for Ezrayel[/91.166.125.23:38301]
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:643) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.network.syncher.EntityDataSerializers$7.copy(EntityDataSerializers.java:147) ~[?:?]
	at net.minecraft.network.syncher.EntityDataSerializers$7.write(EntityDataSerializers.java:134) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData$DataItem.copy(SynchedEntityData.java:344) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData.getAll(SynchedEntityData.java:211) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.<init>(ClientboundSetEntityDataPacket.java:19) ~[?:?]
	at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:285) ~[?:?]
	at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:268) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2397) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2308) ~[?:?]
	at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:2003) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:958) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2140) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2098) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.startTracking(PersistentEntitySectionManager.java:140) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntity(PersistentEntitySectionManager.java:103) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntity(PersistentEntitySectionManager.java:86) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1182) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1089) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItem(CraftWorld.java:774) ~[patched_1.17.1.jar:git-Paper-108]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItem(CraftWorld.java:763) ~[patched_1.17.1.jar:git-Paper-108]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:856) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.world.entity.decoration.ArmorStand.kill(ArmorStand.java:758) ~[?:?]
	at net.minecraft.world.entity.decoration.ArmorStand.hurt(ArmorStand.java:527) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1254) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2003) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onAttack(ServerGamePacketListenerImpl.java:2410) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2337) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-108]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[23:28:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1568) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-108]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-108]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by EvModder** [comment]
This looks pretty serious, I will try and get a fixed version uploaded tonight or tomorrow

**Comment by EvModder** [comment]
The reason this was happening is the `ARMOR_STAND` texture in `plugins/DropHeads/head-textures.txt` was commented-out (disabled) by default, because the line started with `#`. It should have given a more helpful error, but it unfortunately just printed the mess you saw above which made it harder for me to trace down.

I made the error for missing textures more clear, and I enabled the armor_stand head texture by default (currently it is just the oak-planks-block texture)

These changes are in `v3.6.9` which I just uploaded to Bukkit/curseforge, so it should be available soon, in the meantime you can uncomment that line yourself or disable the armor stand head drop by setting the drop chance to 0
