### ISSUE TITLE
ghast head drop error

### ISSUE THREAD

**Issue by matheeuslima** [EvModder/DropHeads#56]
[22:37:04 ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.6.13
java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.world.entity.monster.EntityGhast.getDataWatcher()
        at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:133) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.TextureKeyLookup.getTextureKey(TextureKeyLookup.java:222) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:550) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.attemptHeadDropEvent(EntityDeathListener.java:354) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:572) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:662) ~[DropHeads.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-79]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:868) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1716) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1623) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1451) ~[?:?]
        at net.minecraft.world.entity.monster.Ghast.hurt(Ghast.java:82) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1263) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2502) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2429) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-79]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.entity.monster.EntityGhast.getDataWatcher()
        at java.lang.Class.getDeclaredMethod(Class.java:2675) ~[?:?]
        at net.evmodder.EvLib.extras.ReflectionUtils$RefClass.getMethod(ReflectionUtils.java:132) ~[DropHeads.jar:?]
        ... 35 more

**Comment by LilianLem** [comment]
Same problem here, I just didn't take the time to report it 😅

**Comment by EvModder** [comment]
I figured out why this is happening and I have a patch to fix it, i'll try and get the release out on Bukkit either tomorrow or after Christmas :)

**Comment by EvModder** [comment]
(The bug was with the code which checks for the `Screaming Ghast Head` variant, a Minecraft 1.18 change to the `DataWatcher` field in the `EntityGhast` class caused it to break for all ghasts)

I've fixed this issue in DropHeads v3.6.14 to be compatible with 1.12-1.18+

Side-note: a lot of Mojang-API-related code in DropHeads broke in 1.18, but now that it's fixed it's very unlikely it will break again in future Minecraft updates

**Comment by LilianLem** [comment]
Thanks. Now we're waiting after Bukkit to download the new version
