### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by PlesCZ** [EvModder/DropHeads#58]
`[21:14:56 ERROR]: Could not pass event BlockBreakEvent to DropHeads v3.6.14
java.lang.NullPointerException: Cannot read field "a" because "nextComp" is null
        at net.evmodder.EvLib.extras.TellrawUtils.parseNextComponentFromString(TellrawUtils.java:787) ~[DropHeads.jar:?]
        at net.evmodder.EvLib.extras.TellrawUtils.parseNextComponentFromString(TellrawUtils.java:835) ~[DropHeads.jar:?]
        at net.evmodder.EvLib.extras.TellrawUtils.parseComponentFromString(TellrawUtils.java:1029) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.LoreStoreBlockBreakListener.getItemWithLore(LoreStoreBlockBreakListener.java:44) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.LoreStoreBlockBreakListener.onBlockBreakByPlayerEvent(LoreStoreBlockBreakListener.java:54) ~[DropHeads.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor158.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1562]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:402) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:356) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1838) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1441) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1562]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by EvModder** [comment]
Sorry for getting back so late, but do you by any chance know which block causes this error when broken?
I would be super interested if you could get the NBT of that block/item so I can see why it caused this error message

**Comment by EvModder** [comment]
Either way, it should be fixed in the next release, because I added a check for null :)
