### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PlesCZ** [EvModder/DropHeads#77]
Server version: Pufferfish 1.19.2

`[14:51:26 ERROR]: Could not pass event EntityDeathEvent to DropHeads v3.7.7
java.lang.NullPointerException: Cannot invoke "net.evmodder.DropHeads.LRUCache.get(Object)" because "this.weaponCompCache" is null
        at net.evmodder.DropHeads.DropChanceAPI.getWeaponComponent(DropChanceAPI.java:540) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.DropChanceAPI.getBeheadMessage(DropChanceAPI.java:561) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:697) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:177) ~[DropHeads.jar:?]
        at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:270) ~[DropHeads.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-34]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1755) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1652) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1482) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2067) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2992) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2914) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1363) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1340) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1333) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1467) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by felix642** [comment]
HI @PlesCZ, this issue has been reported in : #74.

@EvModder should update the plugin soon and fix this issue. For now you can add this line at the end of the config file to remove the error : 

weapon-tellraw-component-cache-size: 5

**Comment by EvModder** [comment]
Yup, the fixed version should be [available here](https://dev.bukkit.org/projects/dropheads/files/3964253), I was able to get the patch in [this commit](https://github.com/EvModder/DropHeads/commit/b66a50c96c0778603b8d67309193137fca119898)
