### ISSUE TITLE
InvocationTargetException on vehicle destory

### ISSUE THREAD

**Issue by derech1e** [EvModder/DropHeads#82]
Hey, I found this exception in the console of my Server. I don't have an exact explanation for this, but I think the NullPointer is easy to solve.

```
[15:32:39] [Server thread/ERROR]: Could not pass event VehicleDestroyEvent to DropHeads v3.7.7.2
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:346) ~[DropHeads.jar:?]
	at net.evmodder.EvLib.extras.NBTTagUtils.getTag(NBTTagUtils.java:210) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.JunkUtils.setLore(JunkUtils.java:86) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.HeadAPI.headUtils_makeSkull_wrapper(HeadAPI.java:553) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:626) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.HeadAPI.getHead(HeadAPI.java:663) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:674) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.DropChanceAPI.triggerHeadDropEvent(DropChanceAPI.java:698) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.listeners.EntityDeathListener.onEntityDeath(EntityDeathListener.java:177) ~[DropHeads.jar:?]
	at net.evmodder.DropHeads.listeners.EntityDeathListener$DeathEventExecutor.execute(EntityDeathListener.java:274) ~[DropHeads.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.vehicle.Boat.hurt(Boat.java:202) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1322) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2053) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2982) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2904) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:344) ~[DropHeads.jar:?]
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.c()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:458) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:685) ~[paper-1.19.2.jar:git-Paper-183]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:676) ~[paper-1.19.2.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:28) ~[paper-1.19.2.jar:git-Paper-183]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.evmodder.EvLib.extras.ReflectionUtils$RefMethod$RefExecutor.call(ReflectionUtils.java:344) ~[DropHeads.jar:?]
	... 35 more
```

**Comment by EvModder** [comment]
Oh yep, I had another person report this as well. The issue boils down to heads being enabled for minecarts & item frames, but those entities don't have a head texture defined in the config file and due to some bad code logic it ended up getting to this error in a roundabout way.

I've already made the changes that fix this, but I've been a bit slow getting the next Bukkit/curseforge release finished since I'm trying to knock out a couple things at once. (Should be done by this weekend hopefully)

In the meantime, a workaround you could do to get rid of this error is set the drop-chance to 0 specifically per non-living entity, and then this code won't be reached

**Comment by EvModder** [comment]
Took me a while to get the proper fix for this released on Bukkit, but well it's out now :)
