### ISSUE TITLE
Error in blockplaceevent

### ISSUE THREAD

**Issue by thiagogebrimm** [EvModder/DropHeads#86]
```
[20:41:00 ERROR]: Could not pass event BlockPlaceEvent to DropHeads v3.7.8
java.lang.NullPointerException: Cannot invoke "java.util.List.equals(Object)" because "defaultLore" is null
        at net.evmodder.DropHeads.listeners.LoreStoreBlockPlaceListener.onBlockPlaceEvent(LoreStoreBlockPlaceListener.java:34) ~[DropHeads.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor643.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1842]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:396) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:396) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:590) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2051) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1842]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by EvModder** [comment]
Found the bug, and I will have a fixed version out shortly. In the meantime, there are two workarounds to fix this:
1) change `save-custom-lore` to `false` in your [config.yml](https://github.com/EvModder/DropHeads/blob/master/config.yml)
2) change `show-head-type-in-lore` to `true` (same file)

Either change should fix the problem, but I'm guessing the 1st setting is the one that would be better to disabled in your case

**Comment by thiagogebrimm** [comment]
Solved
