### ISSUE TITLE
Null error when running /gethead command without continuing

### ISSUE THREAD

**Issue by thiagogebrimm** [EvModder/DropHeads#92]
```
[03:36:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gethead' in plugin DropHeads v3.7.10
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:981) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:321) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1905]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: thiagogebrim
        at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at net.evmodder.DropHeads.JunkUtils.getGameProfile(JunkUtils.java:331) ~[DropHeads_v3.7.10.jar:?]
        at net.evmodder.DropHeads.commands.CommandSpawnHead.searchForPlayer(CommandSpawnHead.java:263) ~[DropHeads_v3.7.10.jar:?]
        at net.evmodder.DropHeads.commands.CommandSpawnHead.getHeadFromTargetString(CommandSpawnHead.java:355) ~[DropHeads_v3.7.10.jar:?]
        at net.evmodder.DropHeads.commands.CommandSpawnHead.onCommand(CommandSpawnHead.java:504) ~[DropHeads_v3.7.10.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by EvModder** [comment]
Updated jar has been posted, marking as closed :)
